name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: 🟦 Windows MINGW64
    defaults:
      run:
        shell: msys2 {0}
    env:
      CCACHE_DIR:      "${{ github.workspace }}/.ccache"
      CCACHE_MAXSIZE:  "1000M"
      CCACHE_COMPRESS: "true"
      MINGW_ARCH: mingw64
    steps:
    - name: 🧰 Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: 🟦 Install msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        pacboy: >-
          gcc:p
          cmake:p
          make:p
          ccache:p
          capstone:p
          glfw:p
          file:p
          mbedtls:p
          python:p
          freetype:p
          dlfcn:p
          ninja:p

    - name: 📜 Prepare Cache
      id:    prep-ccache
      shell: bash
      run: |
        mkdir -p "${CCACHE_DIR}"
        echo "::set-output name=dir::$CCACHE_DIR"

    - name: 📜 Restore Cache
      uses:  actions/cache@v1
      id:    cache-ccache
      with:
        path: ${{ steps.prep-ccache.outputs.dir }}
        key: ${{ runner.os }}-build-${{ github.run_id }}
        restore-keys: ${{ runner.os }}-build-

    - name: 🛠️ Build
      run: |
        mkdir -p build
        cd build
        cmake -GNinja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          ..
        cmake --build . --target rpm

    - name: ⬆️ Upload plugin
      uses: actions/upload-artifact@v2
      with:
        name: ImHex RPM Plugin
        path: |
          build/rpm.hexplug
